branch-defaults:
  master:
    environment: gp-site-prod-alpha
  develop:
    environment: gp-site-dev-alpha
environment-defaults:
  tgp-api-test:
    branch: null
    repository: null
global:
  application_name: goodparty.org
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.9.2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-tgp
  sc: git
  workspace_type: Application
